### ISSUE TITLE
When custom port is specified, don't overwrite when connection type is set

### ISSUE THREAD

**Issue by mitchhentges** [bigeyex/brackets-sftp-upload#30]
The UX would be improved if the value of "Port" in "Server Setup" was only changed if the user hasn't edited the input yet. There has been a few times in which I set my port first, then change my connection type - the port is set to 21, and I need to re-put it back to custom value.

*Acceptance criteria:*
- If the "Port" input hasn't been "dirtied"/changed by a human, then change it when "Type" is changed
- If the "Port" input has been "dirtied"/changed by a human, then leave it alone

**Comment by dedo1911** [comment]
The fix has been released and It's available since version 1.3.2.
