### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by CasJam** [bigeyex/brackets-sftp-upload#42]
It would be great to have keyboard shortcuts for the FTP functions.  Specifically a key command to upload all files in the queue (similar to the way Coda FTP works).

**Comment by bigeyex** [comment]
Assigned Ctrl(Cmd)+Shift+U for this.

**Comment by rossideas** [comment]
Is it possible to change the "assigned" shortcuts? I'm looking for a "left hand only reach" option.  Thanks really like your work.

**Comment by bigeyex** [comment]
Ah, left hand only, brilliant idea! Redefining hotkeys is not supported - but I can tell you how! In brackets, select (in menu bar) Help->Show Extensions Folder, then user/bigeyex.brackets-sftp-upload. Edit main.js - change line 70-72 to any shortcut you want.

**Comment by rossideas** [comment]
Thank you.  Worked great!

**Comment by Mitchell64** [comment]
Nice extension! Any chance of it being able to monitor changes to files that are changed, but not by the Brackets editor? For example, I edit .scss files and have another program that automatically compiles the .scss files and generates .css and .css.map files. These .css and .css.map files need to be uploaded, however they aren't flagged as changed by SFTP Upload.
