### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by dedo1911** [bigeyex/brackets-sftp-upload#43]
I got no other extensions loaded in my enviroment.
When i try to upload something on the status tab it says:
Unable to load modules: C:/Users/.../Brackets/extensions/user/bigeyex.brackets-sftp-upload/node/SftpUploadDomain reason: Cannot find module 'scp2'

I know, as of README that "This repo does not include required node modules".
But that has been written in "Notes for developers" so what about me, as normal user, that has installed the extension normally? Is it normal to dont have those modules too?

If yes, this is not actually an issue, but where I can get them and how? There should be an Installation Note in the README too.

Thanks

**Comment by bigeyex** [comment]
hi,

The scp2 module is included and shipped in the extension registry. If you install this plugin through registry there should be no problem then. Please don't use the zip file from github.


Thanks.

**Comment by dedo1911** [comment]
Ok thanks,
I haven't cheked that code yet.
As I installed it with the Github link i had to use npm install in my /node/ folder to fix it.

Thanks for your help.
