### ISSUE TITLE
Uploading max connection attempts reached

### ISSUE THREAD

**Issue by albertmn7** [bigeyex/brackets-sftp-upload#55]
I am trying to upload something that i changed and it doesn't let me upload anything else because it says "Max connections attempts reached" I haven't changed any code or anything on the plugin. HELP PLEASE!!!!

**Comment by bigeyex** [comment]
it's likely that you cannot connect to the server, or you have a wrong credential. 

1. try re-enter your username/password (through server setup button);
2. restart brackets.

**Comment by albertmn7** [comment]
It was working fine before this happened. Either way i fixed it, thanks a lot. 

SOLUTION: Restart Brackets
