### ISSUE TITLE
Plugin Requires Brackets To Restart If Any Errors

### ISSUE THREAD

**Issue by kupoback** [bigeyex/brackets-sftp-upload#70]
Seems like if there is an Authentication Error, directory error, or timeout, the plugin requires brackets to be closed and reopened. A refresh down not work.

**Comment by marcandrews** [comment]
+1

**Comment by jongeyer** [comment]
+1

**Comment by henry1778** [comment]
+1

**Comment by bigeyex** [comment]
fixed.
