### ISSUE TITLE
filter deny/allow sftp upload by file or folder

### ISSUE THREAD

**Issue by bvanev** [bigeyex/brackets-sftp-upload#71]
It would be useful to be able to set a deny or allow filter by file / folder to explicitly permit or deny the uploading of files or folders.

Use Cases:
1. uploading of .ftpsync_settings is not desired.  I do not want to upload the .ftpsync_settings file to my 
public web server for security reasons.  As this file is stored in the root of a project, I cannot use the project wide "Upload on Save" as iuf the ftp settings change, this file gets uploaded.

2. I am working on new functionality that will impact the public project.  I do not want this folder to be pushed to the public server until I have fully tested the new capability.

In both of these cases, it would be very useful to be able to "right-click" a file/folder and set to "Do Not Upload" or "Require Acceptance" to upload.

**Comment by bigeyex** [comment]
"Upload on Save" is not designed for this scenario. The upload panel is made for this - you may ignore files in each upload.

**Comment by bvanev** [comment]
Understandable.  This is one of the features that I would really like to
see in a FTP client.Ignoring individual files on a "per upload" operation
is a bit tedious.  It would be nice to be able to save a list of
files/folders to exclude from auto-upload on save.
